WebRegionalismos/Controllers/DefinicionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebRegionalismos.Models;

namespace WebRegionalismos.Controllers
{
    public class DefinicionController : Controller
    {
        private RepositorioPalabraDefinicion repositorio = new RepositorioPalabraDefinicion();

        private RepositorioPais repoPais = new RepositorioPais();
        private RepositorioIdioma repoIdioma = new RepositorioIdioma();

        public ActionResult Index()
        {
            return View(repositorio.listarDefinicionPalabra());
        }



        public ActionResult Crear()
        {
            List<Pais> listaPaises = new List<Pais>();
            listaPaises = repoPais.ListarPaises();
            ViewBag.ListaPaises = listaPaises;

            List<Idioma> listaIdioma = new List<Idioma>();
            listaIdioma = repoIdioma.ListarIdiomas();
            ViewBag.ListaIdioma = listaIdioma;

            return View();
        }


        [HttpPost]
        public ActionResult Crear(Definicion definicion)
        {
            if (ModelState.IsValid)
            {
                repositorio.AgregarPalabraDefinicion(definicion);
                return RedirectToAction("Index");
            }

            return View(definicion);
        }


        //[HttpPost]
        //public JsonResult Crear(string idPais, string idIdioma, string palabra, string definicion)
        //{
        //    try
        //    {
        //        Palabra _palabra = new Palabra
        //        {
        //            DescripcionPalabra = palabra
        //        };

        //        Definicion _definicion = new Definicion
        //        {
        //            Palabra = _palabra,
        //            IdPais = idPais,
        //            IdIdioma = Convert.ToInt32(idIdioma),
        //            Definicion1 = definicion

        //        };

        //        if (!ModelState.IsValid)
        //            return Json(false);
        //        repositorio.AgregarPalabraDefinicion(_definicion);
        //        return Json(true);
        //    }
        //    catch
        //    {
        //        return Json(false);
        //    }

        //}

        //// GET: Definicion/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Definicion/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Definicion/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: Definicion/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Definicion/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Definicion/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }

}

WebRegionalismos/Controllers/PaisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using WebRegionalismos.Models;

namespace WebRegionalismos.Controllers
{
    public class PaisController : Controller
    {
        private RepositorioPais repositorio = new RepositorioPais();


        public ActionResult Index()
        {
            return View(repositorio.ListarPaises());
        }


        public ActionResult Detalle(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pais pais = repositorio.BuscarPais(id);
            if (pais == null)
            {
                return HttpNotFound();
            }
            return View(pais);
        }


        #region Crear       
        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Crear([Bind(Include = "IdPais,DescripcionPais")] Pais pais)
        {
            if (ModelState.IsValid)
            {
                repositorio.AgregarPais(pais);
                return RedirectToAction("Index");
            }

            return View(pais);
        }
        #endregion

        #region Editar
        public ActionResult Editar(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pais pais = repositorio.BuscarPais(id);
            if (pais == null)
            {
                return HttpNotFound();
            }
            return View(pais);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "IdPais,DescripcionPais")] Pais pais)
        {
            if (ModelState.IsValid)
            {
                repositorio.EditarPais(pais);

                return RedirectToAction("Index");
            }
            return View(pais);
        }


        #endregion

        #region Eliminar

        public ActionResult Eliminar(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pais pais = repositorio.BuscarPais(id);
            if (pais == null)
            {
                return HttpNotFound();
            }
            return View(pais);
        }

        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public ActionResult EliminarConfirmar(string id)
        {
            Pais pais = repositorio.BuscarPais(id);

            repositorio.EliminarPais(pais);

            return RedirectToAction("Index");
        }
        #endregion
        
 
        public ActionResult MostrarListaPaises()
        {
            List<Pais> listaPaises = new List<Pais>();
            listaPaises = repositorio.ListarPaises();
            return View(listaPaises);
        }
    }
}

WebRegionalismos/Controllers/PalabraController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebRegionalismos.Models;


namespace WebRegionalismos.Controllers
{
    public class PalabraController : Controller
    {
        //private RepositorioPalabra repositorio = new RepositorioPalabra();
        private RepositorioPais repoPais = new RepositorioPais();
        private RepositorioIdioma repoIdioma = new RepositorioIdioma();

        // GET: Palabra
        //public ActionResult Index()
        //{
        //    return View(repositorio.ListarPalabras());
        //}

        //public ActionResult Crear()
        //{
        //    List<Pais> listaPaises = new List<Pais>();
        //    listaPaises = repoPais.ListarPaises();
        //    ViewBag.ListaPaises = listaPaises;

        //    List<Idioma> listaIdioma = new List<Idioma>();
        //    listaIdioma = repoIdioma.ListarIdiomas();
        //    ViewBag.ListaIdioma = listaIdioma;

        //    return View();
        //}



    }
}

WebRegionalismos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Web Regionalismos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Web Regionalismos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Inicio", "Index", "Home")</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("País", "Index", "Pais")</li>
                    <li>@Html.ActionLink("Idioma", "Index", "Idioma")</li>
                    <li>@Html.ActionLink("Palabras", "Index", "Palabra")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Polaris Soluciones.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebRegionalismos/Views/Shared/_PiePagina.cshtml
<section class="services wrapper">
    <ul class="clearfix">
        <li class="animated wow fadeInDown">
            <img class="icon" src="~/Content/myTemplate/img/icon1.png" alt="" />
            <span class="separator"></span>
            <h2>Officia Deserunt Mollit</h2>
            <p>
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua voluptate velit esse
                cillum dolore.
            </p>
        </li>
        <li class="animated wow fadeInDown" data-wow-delay=".2s">
            <img class="icon" src="~/Content/myTemplate/img/icon2.png" alt="" />
            <span class="separator"></span>
            <h2>Culpa Killum Dolore</h2>
            <p>aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
        </li>
        <li class="animated wow fadeInDown" data-wow-delay=".4s">
            <img class="icon" src="~/Content/myTemplate/img/icon3.png" alt="" />
            <span class="separator"></span>
            <h2>Elit Tempor Incididunt</h2>
            <p>nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat enim ad minim veniam.</p>
        </li>
    </ul>
</section><!--  End services  -->

WebRegionalismos/Views/Shared/_mytemplate.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @**@

    <meta charset="utf-8">
    <meta name="author" content="pixelhint.com">
    @*<meta name="description" content="Sublime Stunning free HTML5/CSS3 website template" />*@
    <link rel="stylesheet" type="text/css" href="~/Content/myTemplate/css/reset.css">
    <link rel="stylesheet" type="text/css" href="~/Content/myTemplate/css/fancybox-thumbs.css">
    <link rel="stylesheet" type="text/css" href="~/Content/myTemplate/css/fancybox-buttons.css">
    
    <link rel="stylesheet" type="text/css" href="~/Content/myTemplate/css/botones.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/myTemplate/css/etiquetas.css"  />
    <link rel="stylesheet" type="text/css" href="~/Content/myTemplate/css/formularios.css"  />

    <link rel="stylesheet" type="text/css" href="~/Content/myTemplate/css/fancybox.css">
    <link rel="stylesheet" type="text/css" href="~/Content/myTemplate/css/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Content/myTemplate/css/main.css">

    <script type="text/javascript" src="~/Content/myTemplate/js/jquery.js"></script>
    <script type="text/javascript" src="~/Content/myTemplate/js/fancybox.js"></script>
    <script type="text/javascript" src="~/Content/myTemplate/js/fancybox-buttons.js"></script>
    <script type="text/javascript" src="~/Content/myTemplate/js/fancybox-media.js"></script>
    <script type="text/javascript" src="~/Content/myTemplate/js/fancybox-thumbs.js"></script>
    <script type="text/javascript" src="~/Content/myTemplate/js/wow.js"></script>
    <script type="text/javascript" src="~/Content/myTemplate/js/main.js"></script>

</head>
<body>

    <section class="billboard dark">
        <header class="wrapper dark">
            <a href="#"><img class="logo" src="~/Content/myTemplate/img/logo_dark.png" alt="" /></a>
            <nav>
                <ul>
                    <li>@Html.ActionLink("Principal", "Index", "Home")</li>
                    <li>@Html.ActionLink("País", "Index", "Pais")</li>
                    <li>@Html.ActionLink("Idioma", "Index", "Idioma")</li>
                    <li>@Html.ActionLink("Palabras", "Index", "Definicion")</li>
                </ul>
            </nav>
        </header>

        <div class="caption dark animated wow fadeInDown clearfix">
            <h1>@WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblNombreSistema</h1>
            <p>@WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblDescripcionSistema</p>
            <hr>
        </div>
        <div class="shadow"></div>
    </section><!--  End billboard  -->

    <div>
        @RenderBody()
    </div>
</body>
</html>