WebRegionalismos/Models/Idioma.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebRegionalismos.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Idioma
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Idioma()
    {

        this.Definicion = new HashSet<Definicion>();

    }


    public int IdIdioma { get; set; }

    public string DescripcionIdioma { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Definicion> Definicion { get; set; }

}

}

WebRegionalismos/Controllers/IdiomaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebRegionalismos.Models;

namespace WebRegionalismos.Controllers
{
    public class IdiomaController : Controller
    {
        private RepositorioIdioma repositorio = new RepositorioIdioma();
        
        public ActionResult Index()
        {
            return View(repositorio.ListarIdiomas());
        }


        public ActionResult Detalle(Int64 id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Idioma idioma = repositorio.BuscarIdioma(id);
            if (idioma == null)
            {
                return HttpNotFound();
            }
            return View(idioma);
        }

        #region Crear Idioma

       
        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear([Bind(Include = "IdIdioma,DescripcionIdioma")] Idioma idioma)
        {
            if (ModelState.IsValid)
            {
                repositorio.AgregarIdioma(idioma);
                return RedirectToAction("Index");
            }

            return View(idioma);
        }
        #endregion

        #region Editar Idioma

        public ActionResult Editar(Int64 id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Idioma idioma = repositorio.BuscarIdioma(id);
            if (idioma == null)
            {
                return HttpNotFound();
            }
            return View(idioma);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "IdIdioma,DescripcionIdioma")] Idioma idioma)
        {
            if (ModelState.IsValid)
            {
                repositorio.EditarIdioma(idioma);

                return RedirectToAction("Index");
            }
            return View(idioma);
        }
        #endregion

        public ActionResult Eliminar(Int64 id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Idioma idioma = repositorio.BuscarIdioma(id);
            if (idioma == null)
            {
                return HttpNotFound();
            }
            return View(idioma);
        }

        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public ActionResult EliminarConfirmar(Int64 id)
        {
            Idioma idioma = repositorio.BuscarIdioma(id);

            repositorio.EliminarIdioma(idioma);

            return RedirectToAction("Index");
        }

        public ActionResult MostrarTodosIdiomas()
        {
            var idiomas = repositorio.ListarIdiomas();
            return PartialView("_MostrarTodosIdiomas", idiomas);
        }
    }
}

WebRegionalismos/Views/Idioma/Crear.cshtml
@model WebRegionalismos.Models.Idioma

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2 class="titulo">
    Crear Nuevo Idioma
</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-style-3">
        <form>
            <fieldset>
                <legend>Complete la información según corresponda</legend>

                @*<div>
                        @Html.Label(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblIdioma, htmlAttributes: new { @class = "required" })

                        @Html.EditorFor(model => model.IdIdioma, new { htmlAttributes = new { @class = "input-field" } })
                    </div>*@

                <div>
                    @Html.Label(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblNombreIdioma, htmlAttributes: new { @class = "required" })

                    @Html.EditorFor(model => model.DescripcionIdioma, new { htmlAttributes = new { @class = "input-field" } })
                </div>
            </fieldset>

            <div>
                <div>
                    <table class="botonNuevo">
                        <tbody>
                            <tr>
                                <td>
                                    <button type="submit" value="Crear" class="botonGuardarSombreado">
                                        Guardar
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>


        </form>
    </div>
}

<table class="botonNuevo">
    <tbody>
        <tr>
            <td>
                <button class="botonVolverSombreado" onclick="location.href='@Url.Action("Index", "Idioma")'">
                    Volver
                </button>
            </td>
        </tr>
    </tbody>
</table>


@Html.Partial("~/Views/Shared/_PiePagina.cshtml")

WebRegionalismos/Views/Idioma/Detalle.cshtml
@model WebRegionalismos.Models.Idioma

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2 class="titulo">
    Detalle
</h2>


<div class="form-style-3">
    <form>
        <fieldset>
            <legend>Información General</legend>

            <div>
                @Html.DisplayName(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblIdioma)

                @Html.DisplayFor(model => model.IdIdioma)
            </div>

            <div>

                @Html.DisplayName(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblNombreIdioma)

                @Html.DisplayFor(model => model.DescripcionIdioma)

            </div>
        </fieldset>
    </form>
</div>



<div>
    <div>
        <table class="botonNuevo">
            <tbody>
                <tr>
                    <td>
                        <button class="botonEditarSombreado" onclick="location.href='@Url.Action("Editar", "Idioma", new { id = Model.IdIdioma })'">
                            Editar
                        </button>
                    </td>
                    <td>
                        <button class="botonVolverSombreado" onclick="location.href='@Url.Action("Index", "Idioma")'">
                            Volver
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


@Html.Partial("~/Views/Shared/_PiePagina.cshtml")

WebRegionalismos/Views/Idioma/Editar.cshtml
@model WebRegionalismos.Models.Idioma

@{
    /**/

    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2 class="titulo">
    Editar Idioma
</h2>

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    <div class="form-style-3">
        <form>
            <fieldset>
                <legend>Complete la información según corresponda</legend>

                <div>
                    @Html.Label(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblIdioma, htmlAttributes: new { @class = "required" })

                    @Html.EditorFor(model => model.IdIdioma, new { htmlAttributes = new { @class = "input-field", @disabled = "true" } })
                </div>

                <div>
                    @Html.Label(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblNombreIdioma, htmlAttributes: new { @class = "required" })

                    @Html.EditorFor(model => model.DescripcionIdioma, new { htmlAttributes = new { @class = "input-field" } })
                </div>
            </fieldset>

            <div>
                <div>
                    <table class="botonNuevo">
                        <tbody>
                            <tr>
                                <td>
                                    <button type="submit" value="Guardar" class="botonGuardarSombreado">
                                        Guardar
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>



    </div>

}


    <div>
        <div>
            <table class="botonNuevo">
                <tbody>
                    <tr>
                        <td>
                            <button class="botonVolverSombreado" onclick="location.href='@Url.Action("Index", "Idioma")'">
                                Volver
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>






@Html.Partial("~/Views/Shared/_PiePagina.cshtml")

WebRegionalismos/Views/Idioma/Eliminar.cshtml
@model WebRegionalismos.Models.Idioma

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2 class="titulo">
    Eliminar Idioma
</h2>

<h3>¿Confirma que desea eliminar este registro?</h3>

<div>

    <hr />

    <div class="form-style-3">
        <form>
            <fieldset>
                <legend>Información General</legend>

                <div>
                    @Html.DisplayName(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblIdioma)

                    @Html.DisplayFor(model => model.IdIdioma)
                </div>

                <div>

                    @Html.DisplayName(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblNombreIdioma)

                    @Html.DisplayFor(model => model.DescripcionIdioma)

                </div>
            </fieldset>
        </form>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <div>
            <div>
                <table class="botonNuevo">
                    <tbody>
                        <tr>
                            <td>
                                <button type="submit" value="Eliminar" class="botonGuardarSombreado">
                                    Eliminar
                                </button>
                            </td>

                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    }
</div>

<table class="botonNuevo">
    <tbody>
        <tr>

            <td>
                <button class="botonVolverSombreado" onclick="location.href='@Url.Action("Index", "Idioma")'">
                    Volver
                </button>
            </td>
        </tr>
    </tbody>
</table>

@Html.Partial("~/Views/Shared/_PiePagina.cshtml")

WebRegionalismos/Views/Idioma/Index.cshtml
@model IEnumerable<WebRegionalismos.Models.Idioma>

@{
    ViewBag.Title = "Catálogo de Idiomas";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2 class="titulo">
    Catálogo de Idiomas
</h2>


<table class="cinereousTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayName(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblIdioma)
            </th>
            <th>
                @Html.DisplayName(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblNombreIdioma)
            </th>
            <th>
                @Html.DisplayName(WebRegionalismos.Clases_Compartidas.VariablesGlobales.lblOpciones)
            </th>
        </tr>
    </thead>
    <tfoot>

    </tfoot>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdIdioma)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DescripcionIdioma)
                </td>
                <td>

                    <button class="botonEditarSombreado" onclick="location.href='@Url.Action("Editar", "Idioma", new { id = item.IdIdioma })'">
                        Editar
                    </button> |

                    <button class="botonDetalleSombreado" onclick="location.href='@Url.Action("Detalle", "Idioma", new { id = item.IdIdioma })'">
                        Detalle
                    </button> |

                    <button class="botonBorrarSombreado" onclick="location.href='@Url.Action("Eliminar", "Idioma", new { id = item.IdIdioma })'">
                        Eliminar
                    </button>

                </td>
            </tr>
        }
    </tbody>
</table>

















@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DescripcionIdioma)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DescripcionIdioma)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IdIdioma }) |
                @Html.ActionLink("Details", "Details", new { id = item.IdIdioma }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IdIdioma })
            </td>
        </tr>
    }

</table>*@



<div>
    <table class="botonNuevo">
        <tbody>
            <tr>
                <td>Incluir nuevo país:</td>
                <td>
                    <button class="botonNuevoSombreado" onclick="location.href='@Url.Action("Crear", "Idioma")'">
                        Nuevo País
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

@Html.Partial("~/Views/Shared/_PiePagina.cshtml")

WebRegionalismos/Views/Idioma/MostrarTododsIdiomas.cshtml
@model IEnumerable<WebRegionalismos.Models.Idioma>


<select id="SelectIdioma">
    <option disabled selected>Seleccione Idioma</option>
    @foreach (var item in Model)
    {
        <option value=@item.IdIdioma>@Html.DisplayFor(modelItem => item.DescripcionIdioma)</option>
    }
</select>